#EasyCommandBlocker - легкий способ заблокировать команды на сервере minecraft!
#Подробное описание, инструкции и новые версии здесь:
#Права:

deftxt: '&cЭта команда заблокирована!'  # Текст по умолчанию для заблокированных команд
blockColonCommands: 'true'  # Переключатель для работы с командами с двоеточием

BlockCMD:
  - command: 'op'
    message: '&4Эта команда заблокирована администратором.'
    tabCompleter: true  # Скрыть команду из автозаполнения

  - command: 'gm 1'
    message: 'deftxt'  # Использовать текст по умолчанию
    tabCompleter: false  # Команда будет видна в автозаполнении

  - command: 'set time 1'
    message: ''  # Не отображать сообщение при блокировке
    tabCompleter: false  # Команда будет видна в автозаполнении

  - command: 'gamemode creative'
    message: '&eВы не можете менять режим игры.'
    tabCompleter: true  # Скрыть команду из автозаполнения