name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get the version from pom.xml
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=plugin_version::$VERSION"

      - name: Get the latest commit message
        id: get-commit-message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Check if build is needed
        if: contains(steps.get-commit-message.outputs.commit_message, 'no build version')
        run: |
          echo "Build and release skipped due to 'no build version' in commit message."
          exit 0

      - name: Check if tag exists and determine new tag
        id: check-tag
        run: |
          TAG_NAME=v${{ steps.get-version.outputs.plugin_version }}
          echo "Checking if tag $TAG_NAME exists..."
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            COUNTER=1
            while git rev-parse "$TAG_NAME-$COUNTER" >/dev/null 2>&1; do
              COUNTER=$((COUNTER+1))
            done
            TAG_NAME="$TAG_NAME-$COUNTER"
            echo "Tag $TAG_NAME already exists. New tag determined: $TAG_NAME"
          else
            echo "Tag $TAG_NAME does not exist. Proceeding with this tag."
          fi
          echo "::set-output name=release_tag::$TAG_NAME"

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Rename built JAR
        run: |
          ORIGINAL_JAR=$(ls target/*.jar | head -n 1)
          mv "$ORIGINAL_JAR" "target/EasyCommandBlocker_${{ steps.check-tag.outputs.release_tag }}.jar"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.check-tag.outputs.release_tag }}
          release_name: ${{ steps.check-tag.outputs.release_tag }}
          body: ${{ steps.get-commit-message.outputs.commit_message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: "target/EasyCommandBlocker_${{ steps.check-tag.outputs.release_tag }}.jar"
          asset_name: "EasyCommandBlocker_${{ steps.check-tag.outputs.release_tag }}.jar"
          asset_content_type: application/java-archive
